#!/usr/bin/env bash
# Put everything the robot needs in one place, in one command.
#
#   ./scripts/ship_to_robot.sh                     # policy only (same robot)
#   ./scripts/ship_to_robot.sh --runtime           # + the patched C++ runtime
#   ./scripts/ship_to_robot.sh --runtime --probe   # + observation probe
#   ./scripts/ship_to_robot.sh unitree@10.0.0.5    # somewhere other than default
#
# Lands in ~/run8/ on the robot (kept as the name for continuity). Then:
#   bash ~/run8/00_identify_robot.sh
#   bash ~/run8/01_install_policy.sh
#
# Checksums are computed HERE at ship time and written into the manifest the
# robot verifies against, so the manifest cannot go stale behind a regenerated
# policy. See deploy/BRINGUP_CHECKLIST.md.
set -euo pipefail

RUN="${STILT_RUN:-2026-08-31_13-35-11_run9-no-baselinvel}"
ROBOT="unitree@192.168.123.164"
WITH_RUNTIME=0
PROBE_FLAG=""

for arg in "$@"; do
  case "$arg" in
    --runtime) WITH_RUNTIME=1 ;;
    --probe)   PROBE_FLAG="--probe"; WITH_RUNTIME=1 ;;
    *@*)       ROBOT="$arg" ;;
    *) echo "unknown argument: $arg" >&2; exit 1 ;;
  esac
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ONNX="$ROOT/logs/rsl_rl/stilt_g1_velocity/$RUN/$RUN.onnx"
YAML="$ROOT/deploy/config/g1_stilt/deploy.yaml"
OUT="$ROOT/deploy/outbox"

[ -f "$ONNX" ] || { echo "missing policy: $ONNX" >&2; exit 1; }
[ -f "$YAML" ] || { echo "missing config: $YAML" >&2; exit 1; }

# The config must have been generated from THIS run, or the robot gets a
# layout that does not describe the policy it is running.
if ! grep -q "$RUN" "$YAML"; then
  echo "ABORT: $YAML was not generated from $RUN." >&2
  echo "Run: uv run python scripts/generate_deploy_config.py --run logs/rsl_rl/stilt_g1_velocity/$RUN" >&2
  exit 1
fi

INPUT_DIM="$(uv run --project "$ROOT" python -c "
import onnx, sys
m = onnx.load(sys.argv[1])
print(m.graph.input[0].type.tensor_type.shape.dim[-1].dim_value)
" "$ONNX")"
[ -n "$INPUT_DIM" ] || { echo "could not read the ONNX input width" >&2; exit 1; }

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
cp "$ONNX" "$STAGE/policy.onnx"
cp "$YAML" "$STAGE/deploy.yaml"
cp "$OUT"/*.sh "$STAGE/"

echo "== $RUN  ($INPUT_DIM inputs)"
( cd "$STAGE"
  {
    echo "# Generated by ship_to_robot.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Run: $RUN"
    echo "# Verify:  md5sum -c MANIFEST.txt --ignore-missing"
    # The robot has no onnx library, so record the policy's true input width
    # here. 01_install_policy.sh checks deploy.yaml against it — hardcoding a
    # number there goes stale the first time the observation changes.
    echo "# input_dim: $INPUT_DIM"
    # two spaces between hash and name: GNU md5sum -c requires it
    md5 -r policy.onnx deploy.yaml | awk '{print $1"  "$2}'
  } > MANIFEST.txt
  grep -v '^#' MANIFEST.txt | sed 's/^/   /' )

if [ "$WITH_RUNTIME" = "1" ]; then
  echo "== preparing the patched runtime"
  uv run python "$ROOT/scripts/prepare_runtime.py" $PROBE_FLAG | sed 's/^/   /'
  tar czf "$STAGE/runtime.tar.gz" -C "$ROOT/build/runtime" deploy 2>/dev/null
  echo "   packed $(du -h "$STAGE/runtime.tar.gz" | cut -f1)"
fi

echo "== shipping to $ROBOT:~/run8/"
ssh -o ConnectTimeout=10 "$ROBOT" 'mkdir -p ~/run8'
scp -q -o ConnectTimeout=10 "$STAGE"/* "$ROBOT:~/run8/"

if [ "$WITH_RUNTIME" = "1" ]; then
  echo "== unpacking the runtime into ~/unitree_rl_mjlab/"
  ssh -o ConnectTimeout=10 "$ROBOT" '
    mkdir -p ~/unitree_rl_mjlab
    tar xzf ~/run8/runtime.tar.gz -C ~/unitree_rl_mjlab
    find ~/unitree_rl_mjlab -name "._*" -delete
    rm -f ~/run8/runtime.tar.gz
    echo "   unpacked, $(du -sh ~/unitree_rl_mjlab | cut -f1)"'
fi

cat <<NEXT

Done. On the robot, in order:
  ssh $ROBOT
  bash ~/run8/00_identify_robot.sh        # same robot? setup present?
  bash ~/run8/01_install_policy.sh        # install + point the FSM at it
  cd ~/unitree_rl_mjlab/deploy/robots/g1/build && cmake .. && make -j\$(nproc)

Then deploy/BRINGUP_CHECKLIST.md from Part 4 (release the lowcmd channel).
NEXT
